### ISSUE TITLE
Incremental refreshes?

### ISSUE THREAD

**Issue by ldacey** [domoinc/domo-python-sdk#15]
I am using this approach to append data with Workbench:

```
SELECT *
FROM schema.view
WHERE row_key > '!{lastvalue:row_key}!'
```
Is there a way I can do something similar using the API? Sometimes I do not want to replace a dataset which has millions of rows, but appending can be challenging.

Also, I assume that there is no way to upsert data, right? Sometimes I have data which eventually changes so I can't append it, but the dataset might be 10 million rows, so replacing the whole thing is wasteful.

**Comment by yunruiwatts** [comment]
@ldacey I personally haven't used workbench, so I'm not sure what that approach actually does. Are you wanting to know how to append to a dataset using the API, or wanting to know how to append in a particular way?

As for upsert, we do have the capability to have upsert datasets, but they have to be enabled in your instance. There are some caveats to using them, though - you can't do an upsert operation, you update the schema of the dataset to specify one or more columns that will be used to determine if a new row should replace an existing row. Once the schema has been updated, every append to the dataset is actually an upsert. Appending to an upsert dataset is not quite as fast (especially if the dataset is large), and dataflows built on an upsert dataset can take two to three times as long to update because it has to wait for the upsert to be evaluated instead of being able to just use the newly-appended data.

**Comment by ldacey** [comment]
Sorry - I found the help article and it looks like Workbench uses a Query Variable as a convenience feature. I suppose that is something which I should just implement on my end (track the latest date or row_id which I send to Domo separately).

`https://knowledge.domo.com/Connect/Connecting_to_Data_Using_Workbench/Workbench_4/13Workbench_4_FAQs`


Regarding the upserts, I think I can capture the execution_id when the data is loaded through the API to Domo. I am typically loading data from the previous day, so each execution ID represents a day of data, but maybe in a month from now I will need to replace that data with a fresher version. (A common example is repeat data - a case might not have a repeat today, but within the next 30 days the customer might call back and that row of data will be stale in Domo)

So create a simple table like this:
```
date, execution_id
2017-10-11, 674
2017-10-12, 675
```

Then, if I need to add 2017-10-11 data again, I can lookup any previous execution_ids, delete them, and load a fresh version to Domo without having to reload the whole dataset or creating duplicates. Any issues with this approach? 

The other option is to use the 'insert_timestamp' which gets updated each time there is a change. All new rows would be appended to the Domo dataset but only the latest version would be used (perhaps as simple as a select distinct operation, ordering by the insert_timestamp). Seems somewhat wasteful though, especially for large datasets.

**Comment by ldacey** [comment]
![domo_execution](https://user-images.githubusercontent.com/12517855/32172286-06141fb4-bdb6-11e7-9adb-55f43f3b7400.png)


In the UI, as shown in that screenshot, you can delete a data upload. Each upload has an associated execution_id because it was sent over using the stream API. Is it possible to delete an execution_id with the API? 

I am only seeing examples of deleting a stream or the underlying dataset.

**Comment by yunruiwatts** [comment]
No, we don't support that through the API right now.
