### ISSUE TITLE
Customer's voice on improving examples

### ISSUE THREAD

**Issue by CausalReinforcer** [domoinc/domo-python-sdk#17]
Today is my first day knowing Domo's Python SDK. My goal is to pull data from Domo, so that I can analyze it using Python and Pandas.

I installed it easily and get the client id and secrets set up easily. However, it is not easy to understand how to pull data from Domo. For example, how to retrieve a list of datasets available to me?

It would be great to be clear in stating what is the problem to solve from the user perspective in your examples of code. Thank you!

**Comment by checketts** [comment]
Thanks for the feedback! Since you created a client id/secret, I'm guessing you went to the [Dev Portal](https://developer.domo.com) . Is your feedback related to the docs at https://developer.domo.com/docs/dataset/import-and-export-data#Export%20Data ?  Or were you looking at the Quickstart (https://developer.domo.com/docs/dataset/quickstart-4)  Unfortunately I see the quickstart only focused on importing and not exporting data. 

Lastly, were you able to figure out how to do it eventually? Which resources did you use to get there?

Sorry for all the questions, but I am very interested in your feedback.

**Comment by rswingler** [comment]
Also, the "run_examples.py" file is fully executable - it runs through basic operations in each of the SDK's clients. https://github.com/domoinc/domo-python-sdk/blob/master/run_examples.py

For listing datasets, see line 98 of "run_examples.py":
https://github.com/domoinc/domo-python-sdk/blob/master/run_examples.py#L98
