### ISSUE TITLE
Domo Maintenance

### ISSUE THREAD

**Issue by sChalvet** [domoinc/domo-python-sdk#39]
Hi,

I have some scripts that grab a bunch of data from an FTP server and uploads it to Domo.
The data is formatted strangely which is why we needed a custom solution.

As I upload these CSV files using the `data_import_from_file()` I often run across this **Domo Maintenance** issue. I wrote the script to handle it and retry however this happens often enough that I don't want to try to upload files that are too big in case I have to start over multiple times.

The questions are: 

- What is the recommended file size to upload to Domo? 
- Should I try a stream instead?
- Is this a common issue that others are experiencing?
- Is there anyway to avoid this?

See my log output below:
```2019-05-23 08:44:13,662 - logger - INFO - Attempting to APPEND 201901-Orders_part4.csv to Domo datasetID: d4f43122-8add-40be-b905-. 
2019-05-23 08:44:13,662 - logger - INFO - File size: 93.875116 MB. 
2019-05-23 08:47:49,270 - logger - ERROR -  Failed to append 201901-Orders_part4.csv to Domo. Error uploading DataSet: <!DOCTYPE html>

<html>
    <head>
        <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="Expires" content="0" />
        <title>Domo Maintenance</title>
    </head>
    <body>
			<style type="text/css">
				body {
					background-color: #54585a;
					color: #d4d5d6;
					font-size: 14px;
					font-family: Helvetica Neue, Arial, Helvetica, sans-serif;
					padding-top: 94px;
					line-height: 20px;
				}

				.error-page {
					width: 825px;
				}

				.domobot {
					float: left;
					height: 390px;
					width: 285px;
					padding-right: 40px;
					padding-top: 6px;
					text-align: right;
				}

				h1 {
					color: white;
					font-size: 32px;
					line-height: 38px;
					font-weight: 500;
				}

				h2 {
					font-size: 20px;
					font-weight: 200;
					line-height: 27px;
				}

				h3 {
					font-weight: 500;
					font-size: 15px;
				}

				hr {
					border-top: 1px solid #404445;
					border-bottom: 1px solid #7F8283;
					border-left: none;
					border-right: none;
					margin: 28px 0 25px 0;
				}

				a {
					color: #9acbeb;
					text-decoration: none;
				}

				a:hover, a:active {
					text-decoration: underline;
				}

			</style>
			<div class="error-page">
				<div class="domobot"><img src="/error/domo-logo-200.png" width="200" height="200" alt="Domo"/></div>
				<div class="content">
					<h1>Domo is currently undergoing<br/> maintenance.</h1>
					<h2><br/>Thank you for your patience.</h2>
					<hr />
					<h3>Have any questions? Feel free to contact us.</h3>
					<p>Call us toll-free: 800.899.1000<br/>Email: <a href="mailto:support@domo.com">support@domo.com</a></p>
				</div>
			</div>
    </body>
</html>

2019-05-23 08:47:49,271 - logger - INFO - Domo is undergoing Maintenance. Waiting 60 seconds and trying again. 1 attempt(s)
2019-05-23 08:48:49,274 - logger - INFO - Attempting to APPEND 201901-Orders_part4.csv to Domo datasetID: d4f43122-8add-40be-b905-. 
2019-05-23 08:48:49,275 - logger - INFO - File size: 93.875116 MB. 
2019-05-23 08:51:51,909 - logger - INFO - Appended 201901-Orders_part4.csv to Domo.

**Comment by ldacey** [comment]
@sChalvet This seems to be an intermittent issue and does not seem to be related to the size of the data being sent at all

**Comment by guitarhero23** [comment]
@sChalvet Do you still have this issue? I was getting it as well. I reached out to support and they got back to me saying they put a fix in and to see if it still happened. It happened once after that but has been OK the last week or two.

**Comment by murphysean** [comment]
Please let us know if this issue persists, it sounds like there might have been some work to accommodate larger csvs via the upload api.

To answer some of the original Questions

> What is the recommended file size to upload to Domo?

While I don't think we have any published numbers as your results may vary, I wouldn't recommend uploading anything that takes more than a minute or two to upload. (For me that seems to be somewhere around a GB) via a single network call. Basically if the network call is terminated for any reason, you will likely have to re-start the upload as we don't support resume via the dataset api. Anything larger than that I would recommend using the stream api, with chunked parts smaller than that single network limit.

> Should I try a stream instead?

Streams will help you get more performance while uploading to Domo. Essentially it allows you to upload in parallel, and with smaller chunks so that if something goes wrong you have the option to only re-upload a single chunk. If you have the option to spread the load out across a number of agents, then you could each have them maximize there network bandwidth with chunks. I wouldn't try to stream multiple chunks at a time from a single network connection as that will probably just result in each chunk taking a longer amount of time, with an increased risk of timeouts/network interruption for each.

> Is this a common issue that others are experiencing?

We've occasionally seen issues, especially with really large single uploads, in peak conditions when our servers/network are at capacity, or if the data isn't aligned/formatted correctly. In order to reduce risk we encourage good failure, back-off, and re-try algorithms combined with the methods above to break large files into multiple uploads.

We are hoping to get a better file upload api with resume-able, hash/cache headers, and bytes-received information so that scripts can respond better in failure scenarios.

**Comment by murphysean** [comment]
If anyone continues to see issues, feel free to re-open
