### ISSUE TITLE
Page API 

### ISSUE THREAD

**Issue by mpoudel0313** [domoinc/domo-python-sdk#40]
I am using Python API to pull list of all the pages and their subpages in our domo instance. I am an Admin in our domo instance. When I run the script, It only pulls the pages that I am owner or I am shared with. 
I would like to be able to pull all the pages regardless of I am shared or not? 

Is this intentional?

**Comment by mpoudel0313** [comment]
Any update on this?

**Comment by murphysean** [comment]
I've chatted with the team about this, it appears this is intentional, as the client is tied to your user account in your Domo instance. It will filter the pages based on what you have permissions to. We are working on being able to abstract the client from being bound to a specific user, that way you could, for example, bind a specific client to list all pages (Admin).
